# Regenerates _Obfuscar/obfuscar.generated.xml with absolute AssemblySearchPath
# entries pointing at the .NET 8 ref packs actually installed on this machine.
# Without this, Obfuscar errors out as soon as a hardcoded version stops matching
# what is installed (8.0.25 vs 8.0.26 is enough).
#
# Called from RaphosGeometry.csproj's GenerateObfuscarConfig target on Release
# builds. The .generated.xml is gitignored; obfuscar_Release_x64.xml points at it.
# Fails loud (non-zero exit) when no 8.0.x ref pack can be found -- Obfuscar would
# error anyway, and a clear message saves the debugging.
#
# Mirrors RaphosBundleSynera/_Obfuscar/generate-obfuscar.ps1; here two assemblies
# are obfuscated -- the node palette (RaphosGeometry.dll) and the P/Invoke bridge
# (RaphosGeometryInterop.dll), which ships inside the add-in folder.

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$ProjectDir,
    [Parameter(Mandatory=$true)][string]$SyneraDir
)

$ErrorActionPreference = 'Stop'

# Defensive: when MSBuild passes a path ending in `\` inside double quotes,
# Windows command-line parsing reads the trailing `\"` as an escaped quote and
# leaves a stray `"` at the end of the received argument. Strip both that stray
# quote and the trailing backslash so the rest of the script works regardless of
# what made it through the quoting maze.
$ProjectDir = $ProjectDir.TrimEnd('"', '\')
$SyneraDir  = $SyneraDir.TrimEnd('"', '\')

function Get-LatestRefPack {
    param([string]$Root, [string]$Label)
    if (-not (Test-Path $Root)) {
        throw "Ref pack root not found: $Root (looking for $Label)"
    }
    $version = Get-ChildItem -LiteralPath $Root -Directory `
        | Where-Object { $_.Name -match '^8\.0\.\d+$' } `
        | Sort-Object { [version]$_.Name } `
        | Select-Object -Last 1
    if (-not $version) {
        throw "No 8.0.x folder found in $Root (looking for $Label)"
    }
    $candidate = Join-Path $version.FullName 'ref\net8.0'
    if (-not (Test-Path $candidate)) {
        throw "Expected ref folder missing: $candidate"
    }
    return $candidate.TrimEnd('\') + '\'
}

$netCorePath = Get-LatestRefPack `
    -Root 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref' `
    -Label 'Microsoft.NETCore.App.Ref'

$wpfPath = Get-LatestRefPack `
    -Root 'C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref' `
    -Label 'Microsoft.WindowsDesktop.App.Ref'

$syneraPath = $SyneraDir.TrimEnd('\') + '\'

# KeepPublicApi is what makes this safe for a Synera add-in: Synera finds node
# types by their [Guid] on a public class, the graph data types are named in
# every saved .syn, and the node assembly's calls into the interop bridge are
# public API too. Private and internal members are renamed and their strings
# hidden.
$xml = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by _Obfuscar/generate-obfuscar.ps1. Do not edit by hand:
     the AssemblySearchPath entries are rewritten on every Release build to
     match whatever .NET 8 ref pack is installed on this machine. -->
<Include>
  <Var name="RegenerateDebugInfo" value="false" />
  <Var name="MarkedOnly" value="false" />
  <Var name="RenameProperties" value="true" />
  <Var name="RenameEvents" value="true" />
  <Var name="RenameFields" value="true" />
  <Var name="KeepPublicApi" value="true" />
  <Var name="HidePrivateApi" value="true" />
  <Var name="ReuseNames" value="false" />
  <Var name="HideStrings" value="true" />
  <Var name="OptimizeMethods" value="true" />
  <Var name="SuppressIldasm" value="true" />
  <Var name="AnalyzeXaml" value="true" />
  <Var name="UseUnicodeNames" value="false" />
  <Var name="UseKoreanNames" value="true" />
  <Module file="`$(InPath)\RaphosGeometry.dll">
    <SkipType name="*AnonymousType*" skipProperties="true" skipMethods="true" skipFields="true" skipEvents="true" skipStringHiding="true" />
    <SkipType name="^.*\.Resources$" />
  </Module>
  <Module file="`$(InPath)\RaphosGeometryInterop.dll">
    <SkipType name="*AnonymousType*" skipProperties="true" skipMethods="true" skipFields="true" skipEvents="true" skipStringHiding="true" />
  </Module>
  <AssemblySearchPath path="$netCorePath" />
  <AssemblySearchPath path="$wpfPath" />
  <AssemblySearchPath path="$syneraPath" />
</Include>
"@

$outPath = Join-Path $ProjectDir '_Obfuscar\obfuscar.generated.xml'

# Only rewrite when the content actually changed, so file mtimes stay stable
# across no-op rebuilds and MSBuild's incremental caching is not nudged every
# Release build.
$existing = if (Test-Path $outPath) { Get-Content -LiteralPath $outPath -Raw } else { '' }
if ($existing -ne $xml) {
    $xml | Out-File -FilePath $outPath -Encoding utf8 -NoNewline
    Write-Host "Updated $outPath"
} else {
    Write-Host "Unchanged $outPath"
}
Write-Host "  .NET ref pack: $netCorePath"
Write-Host "  WPF ref pack:  $wpfPath"
Write-Host "  Synera:        $syneraPath"
